### ISSUE TITLE
Examples section still references to old dpsim-notebooks repo

### ISSUE THREAD

**Issue by stv0g** [sogno-platform/dpsim-docs#23]
See here:

- https://sogno.energy/dpsim-docs/docs/examples/

which points to

- https://github.com/dpsim-simulator/dpsim-notebooks

**Comment by m-mirz** [comment]
The documentation has moved to the main dpsim repo.

**Comment by stv0g** [comment]
Yes, but the links in the docu are still wrong?

**Comment by stv0g** [comment]
Or, if this is not the correct documentation anymore, can we remove the old pages? Its just confusing to users how find this via Google..

**Comment by m-mirz** [comment]
Yes, we need the docs in the main repo and overwrite the gh-pages branch here.
