### ISSUE TITLE
Adpat Docker file path in build command

### ISSUE THREAD

**Issue by gnakti** [sogno-platform/dpsim-docs#24]
- From:
  - $ docker build -t sogno/dpsim:dev -f Packaging/Docker/Dockerfile.dev . 

- To:
  - $ docker build -t sogno/dpsim:dev -f **packaging**/Docker/Dockerfile.dev .

**Comment by m-mirz** [comment]
@gnakti the docs have moved to the main repo of dpsim https://github.com/sogno-platform/dpsim/tree/master/docs/hugo
